{% set name = "tox" %}
{% set version = "3.1.2" %}
{% set sha256 = "9f0cbcc36e08c2c4ae90d02d3d1f9a62231f974bcbc1df85e8045946d8261059" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - tox = tox.session:run_main
    - tox-quickstart = tox._quickstart:main

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
  run:
    - python
    - py >=1.4.17
    - pluggy >=0.3.0,<1.0
    - virtualenv >=1.11.2
    - setuptools

test:
  imports:
    - tox
  commands:
    - tox --version
    - tox-quickstart --version

about:
  home: https://github.com/tox-dev/tox
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'virtualenv-based automation of test activities'
  description: |
    Tox is a generic virtualenv management and test command line tool you can use for
    - checking your package installs correctly with different Python versions and interpreters
    - running your tests in each of the environments, configuring your test tool of choice
    - acting as a frontend to Continuous Integration servers, greatly reducing boilerplate
      and merging CI and shell-based testing.
  doc_url: https://tox.readthedocs.org
  dev_url: https://github.com/tox-dev/tox

extra:
  recipe-maintainers:
    - cshaley
    - kalefranz
    - sannykr
