{% set version = "4.11.3" %}

package:
  name: tox
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tox/tox-{{ version }}.tar.gz
  sha256: 307993257d792a12a63ff86a0b67a71a5ab2d4a2cc12bbae947115224d4ac3fb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tox = tox.run:run

requirements:
  host:
    - python
    - pip
    - hatchling >=1.18
    - hatch-vcs >=0.3
    - setuptools
    - wheel
  run:
    - python
    - cachetools >=5.3.1
    - chardet >=5.2
    - colorama >=0.4.6
    - filelock >=3.12.3
    - importlib-metadata >=6.8
    - packaging >=23.1
    - platformdirs >=3.10
    - pluggy >=1.3
    - pyproject-api >=1.6.1
    - tomli >=2.0.1
    - typing-extensions >=4.7.1
    - virtualenv >=20.24.3

{% set skip_tests = [
  "build_wheel_in_non_base_pkg_env",
  "deps_remove_recreate",
  "env_log",
  "find_alias_on_path",
  "get_info_uses_hook_path",
  "install_command_no_packages",
  "install_pkg_via",
  "keyboard_interrupt",
  "legacy_cli_flags",
  "local_subprocess",
  "override_incorrect",
  "package_only",
  "parallel_inception",
  "parallel_interrupt",
  "pip_install_constraint_file_create_change",
  "pip_install_constraint_file_new",
  "pip_install_path",
  "pip_install_req_file_req_like",
  "pip_install_requirements_file_deps",
  "pip_pre",
  "pip_req_path",
  "pkg_dep_remove_recreate",
  "pkg_env_dep_remove_recreate",
  "plugin_hooks_and_order",
  "provision_interrupt_child",
  "provision_non_canonical_dep",
  "pyproject_deps_from_static",
  "pyproject_deps_static_with_dynamic",
  "pyproject_no_build_editable_fallback",
  "python_disable_hash_seed",
  "python_generate_hash_seed",
  "python_keep_hash_seed",
  "python_set_hash_seed",
  "requirements_txt",
  "skip_develop_mode",
  "some_files_exist",
  "tox_install_pkg_sdist",
  "tox_install_pkg_wheel",
  "verbosity_guess_miss_match",
] | join(" or ") %}

test:
  source_files:
    - tests
  requires:
    - python-build >=0.10
    - covdefaults >=2.3
    - detect-test-pollution >=1.1.1
    - devpi-process >=1
    - diff-cover >=7.7
    - distlib >=0.3.7
    - flaky >=3.7
    - hatch-vcs >=0.3
    - hatchling >=1.18
    - psutil >=5.9.5
    - pytest >=7.4
    - pytest-mock >=3.11.1
    - pytest-xdist >=3.3.1
    - re-assert >=1.1
    - time-machine >=2.12
  imports:
    - tox
  commands:
    - pip check
    - tox --version
    - tox --help
    - pytest -v -k "not ({{ skip_tests }})"

about:
  home: https://tox.wiki
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: virtualenv-based automation of test activities
  description: |
    Tox is a generic virtualenv management and test command line tool you can use for
    - checking your package installs correctly with different Python versions and interpreters
    - running your tests in each of the environments, configuring your test tool of choice
    - acting as a frontend to Continuous Integration servers, greatly reducing boilerplate
      and merging CI and shell-based testing.
  doc_url: https://tox.readthedocs.org
  dev_url: https://github.com/tox-dev/tox

extra:
  recipe-maintainers:
    - cshaley
    - kalefranz
    - sannykr
    - bollwyvl
